/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.loginDAO;
import DTO.LoginDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soare
 */
public class jfrmUsuario extends javax.swing.JFrame {

    /**
     * Creates new form jfrmUsuario
     */
    public jfrmUsuario() {
        initComponents();
        listarValores();
        cbxpermissao.addItem("Paciente");
        cbxpermissao.addItem("Funcionário");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cbxpermissao = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        btnAlterUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnCadastrarUsuario = new javax.swing.JButton();
        btnCarregarUsuario = new javax.swing.JButton();
        btnLimparUsuario = new javax.swing.JButton();
        btnVoltarLogin = new javax.swing.JButton();
        txtcodpaci = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do Usuário");

        jLabel2.setText("Senha");

        jLabel3.setText("Pemissão:");

        cbxpermissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxpermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxpermissaoActionPerformed(evt);
            }
        });

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "USUARIO", "PERMISSÃO",
            }
        )
    );
    jScrollPane1.setViewportView(tabelaUsuario);

    btnAlterUsuario.setText("Alterar");
    btnAlterUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAlterUsuarioActionPerformed(evt);
        }
    });

    btnExcluirUsuario.setText("Excluir");
    btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExcluirUsuarioActionPerformed(evt);
        }
    });

    btnCadastrarUsuario.setText("Cadastrar");
    btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCadastrarUsuarioActionPerformed(evt);
        }
    });

    btnCarregarUsuario.setText("Carregar Campos");
    btnCarregarUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCarregarUsuarioActionPerformed(evt);
        }
    });

    btnLimparUsuario.setText("Limpar");
    btnLimparUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimparUsuarioActionPerformed(evt);
        }
    });

    btnVoltarLogin.setText("Voltar ao Login");
    btnVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnVoltarLoginActionPerformed(evt);
        }
    });

    txtcodpaci.setEnabled(false);
    txtcodpaci.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtcodpaciActionPerformed(evt);
        }
    });

    txtcodigo.setEnabled(false);
    txtcodigo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtcodigoActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxpermissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCadastrarUsuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCarregarUsuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimparUsuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAlterUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnExcluirUsuario))
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVoltarLogin)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(30, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(txtcodpaci, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(8, 8, 8)
            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cbxpermissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCadastrarUsuario)
                .addComponent(btnCarregarUsuario)
                .addComponent(btnLimparUsuario)
                .addComponent(btnAlterUsuario)
                .addComponent(btnExcluirUsuario))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnVoltarLogin)
            .addContainerGap(23, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(txtcodpaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxpermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxpermissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxpermissaoActionPerformed

    private void btnAlterUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterUsuarioActionPerformed
        AlterarPaciente();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnAlterUsuarioActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        ExcluirPaciente();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        String nomeUsuario, senha, permissao;
        int codigoUsuario = 0;

        nomeUsuario = txtusuario.getText();
        senha = new String(txtsenha.getPassword());
        permissao = cbxpermissao.getSelectedItem().toString();

        LoginDTO usuarioDTO = new LoginDTO();
        usuarioDTO.setCodigo(codigoUsuario);
        usuarioDTO.setUsuario(nomeUsuario);
        usuarioDTO.setSenha(senha);
        usuarioDTO.setPermissao(permissao);

        loginDAO cadastrarUsuarioDAO = new loginDAO();
        cadastrarUsuarioDAO.cadastrarUsuario(usuarioDTO);

        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void btnCarregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarUsuarioActionPerformed
        CarregarValores();
    }//GEN-LAST:event_btnCarregarUsuarioActionPerformed

    private void btnLimparUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparUsuarioActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparUsuarioActionPerformed

    private void btnVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLoginActionPerformed
        jfrmLogin telaLogin = new jfrmLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnVoltarLoginActionPerformed

    private void txtcodpaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodpaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodpaciActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterUsuario;
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnCarregarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnLimparUsuario;
    private javax.swing.JButton btnVoltarLogin;
    private javax.swing.JComboBox<String> cbxpermissao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodpaci;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
  private void listarValores() {
        loginDAO usuarioDAO = new loginDAO();
        DefaultTableModel model = (DefaultTableModel) tabelaUsuario.getModel();
        model.setNumRows(0);
        ArrayList<LoginDTO> listaUsuarios = usuarioDAO.listarUsuarios();
        for (LoginDTO usuario : listaUsuarios) {
            model.addRow(new Object[]{
                usuario.getCodigo(),
                usuario.getUsuario(),
                usuario.getSenha(),
                usuario.getPermissao()
            // Adicione mais colunas conforme necessário
            });
        }
    }

    private void CarregarValores() {
        int setar = tabelaUsuario.getSelectedRow();

        txtcodigo.setText(tabelaUsuario.getModel().getValueAt(setar, 0).toString());
        txtusuario.setText(tabelaUsuario.getModel().getValueAt(setar, 1).toString());
        txtsenha.setText(tabelaUsuario.getModel().getValueAt(setar, 2).toString());
        cbxpermissao.setSelectedItem(tabelaUsuario.getModel().getValueAt(setar, 3).toString());
    }

    private void LimparCampos() {
        txtcodigo.setText("");
        txtusuario.setText("");
        txtsenha.setText("");
        cbxpermissao.setSelectedIndex(0);

        txtusuario.requestFocus();

    }

    private void AlterarPaciente() {
        int codigoUsuario;
        String nomeUsuario, senha, permissao;
        codigoUsuario = Integer.parseInt(txtcodigo.getText());
        nomeUsuario = txtusuario.getText();
        senha = txtsenha.getText();
        permissao = cbxpermissao.getSelectedItem().toString();

        LoginDTO usuarioDTO = new LoginDTO();
        usuarioDTO.setCodigo(codigoUsuario);
        usuarioDTO.setUsuario(nomeUsuario);
        usuarioDTO.setSenha(senha);
        usuarioDTO.setPermissao(permissao);

        loginDAO usuarioDAO = new loginDAO();
        usuarioDAO.alterarUsuario(usuarioDTO);

    }

    private void ExcluirPaciente() {
        String codigoUsuarioStr = txtcodigo.getText();

        if (!codigoUsuarioStr.isEmpty()) {
            try {
                int codigoUsuario = Integer.parseInt(codigoUsuarioStr);

                LoginDTO usuarioDTO = new LoginDTO();
                usuarioDTO.setCodigo(codigoUsuario);

                loginDAO usuarioDAO = new loginDAO();
                usuarioDAO.excluirUsuario(usuarioDTO);

                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor, insira um código de usuário válido.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, insira um código de usuário.");
        }
    }
}
