/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.FuncionarioDAO;
import DAO.PlantaoDAO;
import DAO.VacinaDAO;
import DTO.PlantaoDTO;
import DTO.VacinaDTO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soare
 */
public class jfrmPlantao extends javax.swing.JFrame {

    /**
     * Creates new form jfrmPlantao
     */
    public jfrmPlantao() {
        initComponents();
        listarValores();
        carregarCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxEnfermeiros = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txthorasaida = new javax.swing.JTextField();
        btnLimparPlantao = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtcodplantao = new javax.swing.JTextField();
        txthoraentrada = new javax.swing.JTextField();
        btnCadastrarPlantao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPlantao = new javax.swing.JTable();
        btnCarregarPlantao = new javax.swing.JButton();
        cbxMedicos = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtdataplant = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxEnfermeiros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel11.setText("Hora Entrada:");

        txthorasaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorasaidaActionPerformed(evt);
            }
        });

        btnLimparPlantao.setText("Limpar");
        btnLimparPlantao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPlantaoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        txtcodplantao.setEnabled(false);
        txtcodplantao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodplantaoActionPerformed(evt);
            }
        });

        txthoraentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraentradaActionPerformed(evt);
            }
        });

        btnCadastrarPlantao.setText("Cadastrar");
        btnCadastrarPlantao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPlantaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Enermeiro(a)");

        jLabel1.setText("Médico(a)");

        tabelaPlantao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "ENF", "ENTRADA", "SAIDA", "DATA", "MED"
            }
        )
    );
    jScrollPane1.setViewportView(tabelaPlantao);

    btnCarregarPlantao.setText("Carregar Campos");
    btnCarregarPlantao.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCarregarPlantaoActionPerformed(evt);
        }
    });

    cbxMedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

    jLabel12.setText("Hora Saída:");

    txtdataplant.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtdataplantActionPerformed(evt);
        }
    });

    jLabel13.setText("Data");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(62, 62, 62)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addGap(116, 116, 116))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtdataplant, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(118, 118, 118))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txthoraentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txthorasaida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnCadastrarPlantao)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarregarPlantao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimparPlantao)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodplantao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbxEnfermeiros, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbxMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jLabel12)
                .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtdataplant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(218, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcodplantao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEnfermeiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthoraentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthorasaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarPlantao)
                    .addComponent(btnCarregarPlantao)
                    .addComponent(btnLimparPlantao)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthorasaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorasaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasaidaActionPerformed

    private void btnLimparPlantaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPlantaoActionPerformed
        //LimparCampos();
    }//GEN-LAST:event_btnLimparPlantaoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarPlantao();
        listarValores();
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtcodplantaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodplantaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodplantaoActionPerformed

    private void txthoraentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraentradaActionPerformed

    private void btnCadastrarPlantaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPlantaoActionPerformed

        String nomeEnfermeiro, nomeMedico, horarioEntrada, horarioSaida;
        Date dataPlantao;
        int codigoEnfermeiro, codigoMedico, codigoPlantao = 0;

        nomeEnfermeiro = cbxEnfermeiros.getSelectedItem().toString();
        nomeMedico = cbxMedicos.getSelectedItem().toString();
        horarioEntrada = txthoraentrada.getText();
        horarioSaida = txthorasaida.getText();

        try {
            java.util.Date utilDate = new SimpleDateFormat("dd/MM/yyyy").parse(txtdataplant.getText());
            dataPlantao = new java.sql.Date(utilDate.getTime());
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao converter a data do plantão.");
            return;
        }

        codigoEnfermeiro = obterCodigoFuncionarioPorNome(nomeEnfermeiro);
        codigoMedico = obterCodigoFuncionarioPorNome(nomeMedico);

        PlantaoDTO plantaoDTO = new PlantaoDTO();
        plantaoDTO.setCodigoPlantaoEnfermeiro(codigoPlantao);
        plantaoDTO.setCodigoEnfermeiro(codigoEnfermeiro);
        plantaoDTO.setHorarioEntrada(horarioEntrada);
        plantaoDTO.setHorarioSaida(horarioSaida);
        plantaoDTO.setDataPlantao(dataPlantao);
        plantaoDTO.setCodigoMedico(codigoMedico);

        PlantaoDAO plantaoDAO = new PlantaoDAO();

        plantaoDAO.cadastrarPlantao(plantaoDTO);

        listarValores();
        limparCampos();

    }//GEN-LAST:event_btnCadastrarPlantaoActionPerformed

    private void btnCarregarPlantaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarPlantaoActionPerformed
        carregarValores();
    }//GEN-LAST:event_btnCarregarPlantaoActionPerformed

    private void txtdataplantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdataplantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataplantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmPlantao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmPlantao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmPlantao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmPlantao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmPlantao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrarPlantao;
    private javax.swing.JButton btnCarregarPlantao;
    private javax.swing.JButton btnLimparPlantao;
    private javax.swing.JComboBox<String> cbxEnfermeiros;
    private javax.swing.JComboBox<String> cbxMedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPlantao;
    private javax.swing.JTextField txtcodplantao;
    private javax.swing.JTextField txtdataplant;
    private javax.swing.JTextField txthoraentrada;
    private javax.swing.JTextField txthorasaida;
    // End of variables declaration//GEN-END:variables

    private void carregarCombobox() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();

        ArrayList<String> nomesMedicos = funcionarioDAO.recuperarNomesMedicos();
        for (String nome : nomesMedicos) {
            cbxMedicos.addItem(nome);
        }

        ArrayList<String> nomesEnfermeiros = funcionarioDAO.recuperarNomesEnfermeiros();
        for (String nome : nomesEnfermeiros) {
            cbxEnfermeiros.addItem(nome);
        }
    }

    private void listarValores() {
        try {
            PlantaoDAO plantaoDAO = new PlantaoDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaPlantao.getModel();
            model.setNumRows(0);

            ArrayList<PlantaoDTO> lista = plantaoDAO.pesquisarPlantao();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getCodigoPlantaoEnfermeiro(),
                    lista.get(num).getCodigoEnfermeiro(),
                    lista.get(num).getHorarioEntrada(),
                    lista.get(num).getHorarioSaida(),
                    lista.get(num).getDataPlantao(),
                    lista.get(num).getCodigoMedico()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro JFPlantao" + e);
        }
    }

    private void carregarValores() {
        int setar = tabelaPlantao.getSelectedRow();

        txtcodplantao.setText(tabelaPlantao.getModel().getValueAt(setar, 0).toString());
        cbxEnfermeiros.setSelectedItem(tabelaPlantao.getModel().getValueAt(setar, 1).toString());
        txthoraentrada.setText(tabelaPlantao.getModel().getValueAt(setar, 2).toString());
        txthorasaida.setText(tabelaPlantao.getModel().getValueAt(setar, 3).toString());
        txtdataplant.setText(tabelaPlantao.getModel().getValueAt(setar, 4).toString());
        cbxMedicos.setSelectedItem(tabelaPlantao.getModel().getValueAt(setar, 5).toString());
    }

    private void limparCampos() {
        txtcodplantao.setText("");
        cbxEnfermeiros.setSelectedIndex(0);
        cbxMedicos.setSelectedIndex(0);
        txthoraentrada.setText("");
        txthorasaida.setText("");
        txtdataplant.setText("");
    }

    private void alterarPlantao() {
        int codigoPlantao;
        String horarioEntrada, horarioSaida, nomeEnfermeiro, nomeMedico;
        Date dataPlantao;

        codigoPlantao = Integer.parseInt(txtcodplantao.getText());
        nomeEnfermeiro = cbxEnfermeiros.getSelectedItem().toString();
        nomeMedico = cbxMedicos.getSelectedItem().toString();
        horarioEntrada = txthoraentrada.getText();
        horarioSaida = txthorasaida.getText();

        try {
            java.util.Date utilDate = new SimpleDateFormat("dd/MM/yyyy").parse(txtdataplant.getText());
            dataPlantao = new java.sql.Date(utilDate.getTime());
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao converter a data de vacinação.");
            return;
        }

        int codigoEnf = obterCodigoFuncionarioPorNome(nomeEnfermeiro);
        int codigoMed = obterCodigoFuncionarioPorNome(nomeMedico);

        PlantaoDTO plantaoDTO = new PlantaoDTO();
        plantaoDTO.setCodigoPlantaoEnfermeiro(codigoPlantao);
        plantaoDTO.setCodigoEnfermeiro(codigoEnf);
        plantaoDTO.setHorarioEntrada(horarioEntrada);
        plantaoDTO.setHorarioSaida(horarioSaida);
        plantaoDTO.setDataPlantao(dataPlantao);
        plantaoDTO.setCodigoMedico(codigoMed);

        PlantaoDAO plantaoDAO = new PlantaoDAO();
        plantaoDAO.alterarPlantao(plantaoDTO);
    }

    private int obterCodigoFuncionarioPorNome(String nomeFuncionario) {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        return funcionarioDAO.obterCodigoFuncionarioPorNome(nomeFuncionario);
    }
}
