package VIEW;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.VacinaDAO;
import DTO.VacinaDTO;

public class jfrmVacina extends javax.swing.JFrame {

    /**
     * Creates new form jfrmVacina
     */
    public jfrmVacina() {
        initComponents();
        listarValores();
        cbxviaAdministracao.addItem("Parenteral");
        cbxviaAdministracao.addItem("Oral");

        cbxformaAdministracao.addItem("Gotas");
        cbxformaAdministracao.addItem("Intramuscular");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtnomeVacina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcodigoVacina = new javax.swing.JTextField();
        txtlugarAdministracao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxviaAdministracao = new javax.swing.JComboBox<>();
        cbxformaAdministracao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVacina = new javax.swing.JTable();
        btnLimparVacina = new javax.swing.JButton();
        btnAlterarVacina = new javax.swing.JButton();
        btnExcluirVacina = new javax.swing.JButton();
        btnCadastrarVacina = new javax.swing.JButton();
        btnCarregarVacina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Forma Administração");

        jLabel3.setText("ID");

        jLabel11.setText("Lugar Administração");

        txtcodigoVacina.setEnabled(false);
        txtcodigoVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoVacinaActionPerformed(evt);
            }
        });

        txtlugarAdministracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlugarAdministracaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Via Administração");

        jLabel1.setText("Nome Vacina");

        cbxviaAdministracao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        cbxformaAdministracao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel4.setText("Descrição");

        tabelaVacina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "FORMA ADM", "VIA ADM", "LUGAR ADM", "DESCRIÇÃO"
            }
        )
    );
    jScrollPane1.setViewportView(tabelaVacina);

    btnLimparVacina.setText("Limpar");
    btnLimparVacina.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimparVacinaActionPerformed(evt);
        }
    });

    btnAlterarVacina.setText("Alterar");
    btnAlterarVacina.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAlterarVacinaActionPerformed(evt);
        }
    });

    btnExcluirVacina.setText("Excluir");
    btnExcluirVacina.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExcluirVacinaActionPerformed(evt);
        }
    });

    btnCadastrarVacina.setText("Cadastrar");
    btnCadastrarVacina.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCadastrarVacinaActionPerformed(evt);
        }
    });

    btnCarregarVacina.setText("Carregar Campos");
    btnCarregarVacina.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCarregarVacinaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtdescricao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(cbxformaAdministracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(cbxviaAdministracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtlugarAdministracao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtcodigoVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(txtnomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnCadastrarVacina)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCarregarVacina)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLimparVacina)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnAlterarVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnExcluirVacina)))
            .addContainerGap(22, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(5, 5, 5))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtcodigoVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtnomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel6)
                .addComponent(jLabel11))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbxformaAdministracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbxviaAdministracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtlugarAdministracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCadastrarVacina)
                .addComponent(btnCarregarVacina)
                .addComponent(btnLimparVacina)
                .addComponent(btnAlterarVacina)
                .addComponent(btnExcluirVacina))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoVacinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoVacinaActionPerformed

    private void txtlugarAdministracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlugarAdministracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlugarAdministracaoActionPerformed

    private void btnLimparVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparVacinaActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparVacinaActionPerformed

    private void btnAlterarVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVacinaActionPerformed
        AlterarVacina();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnAlterarVacinaActionPerformed

    private void btnExcluirVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirVacinaActionPerformed
        ExcluirVacina();
        listarValores();
        LimparCampos();
    }//GEN-LAST:event_btnExcluirVacinaActionPerformed

    private void btnCadastrarVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVacinaActionPerformed
        cadastrarVacina();
    }//GEN-LAST:event_btnCadastrarVacinaActionPerformed

    private void btnCarregarVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarVacinaActionPerformed
        CarregarValores();
    }//GEN-LAST:event_btnCarregarVacinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmVacina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarVacina;
    private javax.swing.JButton btnCadastrarVacina;
    private javax.swing.JButton btnCarregarVacina;
    private javax.swing.JButton btnExcluirVacina;
    private javax.swing.JButton btnLimparVacina;
    private javax.swing.JComboBox<String> cbxformaAdministracao;
    private javax.swing.JComboBox<String> cbxviaAdministracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVacina;
    private javax.swing.JTextField txtcodigoVacina;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtlugarAdministracao;
    private javax.swing.JTextField txtnomeVacina;
    // End of variables declaration//GEN-END:variables

    private void listarValores() {
        try {
            VacinaDAO vacinaDAO = new VacinaDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaVacina.getModel();
            model.setNumRows(0);

            ArrayList<VacinaDTO> listaVacinas = vacinaDAO.pesquisarVacina();

            for (int num = 0; num < listaVacinas.size(); num++) {
                model.addRow(new Object[]{
                    listaVacinas.get(num).getCodigoVacina(),
                    listaVacinas.get(num).getNomeVacina(),
                    listaVacinas.get(num).getFormaAdministracao(),
                    listaVacinas.get(num).getViaAdministracao(),
                    listaVacinas.get(num).getLugarAdministracao(),
                    listaVacinas.get(num).getDescricao()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar vacinas: " + e);
        }
    }

    private void CarregarValores() {
        int setar = tabelaVacina.getSelectedRow();

        txtcodigoVacina.setText(tabelaVacina.getModel().getValueAt(setar, 0).toString());
        txtnomeVacina.setText(tabelaVacina.getModel().getValueAt(setar, 1).toString());
        cbxformaAdministracao.setSelectedItem(tabelaVacina.getModel().getValueAt(setar, 2).toString());
        cbxviaAdministracao.setSelectedItem(tabelaVacina.getModel().getValueAt(setar, 3).toString());
        txtlugarAdministracao.setText(tabelaVacina.getModel().getValueAt(setar, 4).toString());
        txtdescricao.setText(tabelaVacina.getModel().getValueAt(setar, 5).toString());
    }

    private void LimparCampos() {
        txtcodigoVacina.setText("");
        txtnomeVacina.setText("");
        cbxformaAdministracao.setSelectedIndex(0);
        cbxviaAdministracao.setSelectedIndex(0);
        txtlugarAdministracao.setText("");
        txtdescricao.setText("");

        txtnomeVacina.requestFocus();
    }

    private void AlterarVacina() {
        int codigoVacina;
        String nomeVacina, formaAdministracao, viaAdministracao, lugarAdministracao = null, descricao;

        codigoVacina = Integer.parseInt(txtcodigoVacina.getText());
        nomeVacina = txtnomeVacina.getText();
        formaAdministracao = cbxformaAdministracao.getSelectedItem().toString();
        viaAdministracao = cbxviaAdministracao.getSelectedItem().toString();
        lugarAdministracao = txtlugarAdministracao.getText();
        descricao = txtdescricao.getText();
        VacinaDTO vacinaDTO = new VacinaDTO();
        vacinaDTO.setCodigoVacina(codigoVacina);
        vacinaDTO.setNomeVacina(nomeVacina);
        vacinaDTO.setFormaAdministracao(formaAdministracao);
        vacinaDTO.setViaAdministracao(viaAdministracao);
        vacinaDTO.setLugarAdministracao(lugarAdministracao);
        vacinaDTO.setDescricao(descricao);

        VacinaDAO vacinaDAO = new VacinaDAO();
        vacinaDAO.alterarVacina(vacinaDTO);
    }

    private void ExcluirVacina() {
        int codigoVacina;

        codigoVacina = Integer.parseInt(txtcodigoVacina.getText());

        VacinaDTO vacinaDTO = new VacinaDTO();
        vacinaDTO.setCodigoVacina(codigoVacina);

        VacinaDAO vacinaDAO = new VacinaDAO();
        vacinaDAO.excluirVacina(vacinaDTO);
    }

    private void cadastrarVacina() {
        String nomeVacina, formaAdministracao, viaAdministracao, lugarAdministracao = null, descricao;

        nomeVacina = txtnomeVacina.getText();
        formaAdministracao = cbxformaAdministracao.getSelectedItem().toString();
        viaAdministracao = cbxviaAdministracao.getSelectedItem().toString();
        lugarAdministracao = txtlugarAdministracao.getText();
        descricao = txtdescricao.getText();

        VacinaDTO vacinaDTO = new VacinaDTO();
        vacinaDTO.setNomeVacina(nomeVacina);
        vacinaDTO.setFormaAdministracao(formaAdministracao);
        vacinaDTO.setViaAdministracao(viaAdministracao);
        vacinaDTO.setLugarAdministracao(lugarAdministracao);
        vacinaDTO.setDescricao(descricao);

        VacinaDAO vacinaDAO = new VacinaDAO();
        vacinaDAO.cadastrarVacina(vacinaDTO);

        listarValores();
        LimparCampos();
    }

}
